/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS17051204033;

import java.awt.Toolkit;

/**
 *
 * @author Husni
 */
public class formKalkulatorGL extends javax.swing.JFrame {

    /**
     * Creates new form formKalkulatorGL
     */
    public formKalkulatorGL() {
        initComponents();
        setIcon();
    }

    int satu;
    int dua;
    int hasil;
    String error="hasil gerbang logika : error";
    String nol ="Hasil gerbang logika : 0";
    String satu1 ="Hasil gerbang logika : 1";
    String nol_1 ="0";
    String nol_2 ="0";
    String satu_1 ="1";
    String satu_2 ="1";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Btn_And = new javax.swing.JButton();
        Btn_Or = new javax.swing.JButton();
        Btn_Not = new javax.swing.JButton();
        Btn_Nand = new javax.swing.JButton();
        Btn_Nor = new javax.swing.JButton();
        Lbl_1 = new javax.swing.JLabel();
        Lbl_2 = new javax.swing.JLabel();
        Lbl_Hasil = new javax.swing.JLabel();
        Btn_Xor = new javax.swing.JButton();
        Btn_Xnor = new javax.swing.JButton();
        Btn_Reset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Btn_0_1 = new javax.swing.JButton();
        Btn_1_1 = new javax.swing.JButton();
        Btn_0_2 = new javax.swing.JButton();
        Btn_1_2 = new javax.swing.JButton();
        Lbl_masukkan1 = new javax.swing.JLabel();
        Lbl_masukkan2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uji Gerbang Logika");
        setResizable(false);

        Btn_And.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS17051204033/and.png"))); // NOI18N
        Btn_And.setMaximumSize(new java.awt.Dimension(72, 35));
        Btn_And.setMinimumSize(new java.awt.Dimension(72, 35));
        Btn_And.setPreferredSize(new java.awt.Dimension(72, 35));
        Btn_And.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AndActionPerformed(evt);
            }
        });

        Btn_Or.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS17051204033/or.png"))); // NOI18N
        Btn_Or.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OrActionPerformed(evt);
            }
        });

        Btn_Not.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS17051204033/125px-Logic-gate-inv-us.png"))); // NOI18N
        Btn_Not.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NotActionPerformed(evt);
            }
        });

        Btn_Nand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS17051204033/nand.png"))); // NOI18N
        Btn_Nand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NandActionPerformed(evt);
            }
        });

        Btn_Nor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS17051204033/nor.png"))); // NOI18N
        Btn_Nor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NorActionPerformed(evt);
            }
        });

        Lbl_1.setText("Masukkan 1 : ");

        Lbl_2.setText("Masukkan 2 : ");

        Lbl_Hasil.setText("Hasil gerbang logika :  ");

        Btn_Xor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS17051204033/xor.png"))); // NOI18N
        Btn_Xor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_XorActionPerformed(evt);
            }
        });

        Btn_Xnor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS17051204033/xnor.png"))); // NOI18N
        Btn_Xnor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_XnorActionPerformed(evt);
            }
        });

        Btn_Reset.setText("reset");
        Btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ResetActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Uji Gerbang Logika");

        Btn_0_1.setText("0");
        Btn_0_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_0_1ActionPerformed(evt);
            }
        });

        Btn_1_1.setText("1");
        Btn_1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_1_1ActionPerformed(evt);
            }
        });

        Btn_0_2.setText("0");
        Btn_0_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_0_2ActionPerformed(evt);
            }
        });

        Btn_1_2.setText("1");
        Btn_1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_1_2ActionPerformed(evt);
            }
        });

        Lbl_masukkan1.setText("-");

        Lbl_masukkan2.setText("-");

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_And, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Or, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Not, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Nand, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Nor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Xor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Xnor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Reset))
                            .addComponent(Lbl_Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Lbl_2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Lbl_masukkan2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Lbl_1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Lbl_masukkan1)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn_0_1)
                                        .addGap(4, 4, 4)
                                        .addComponent(Btn_1_1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn_0_2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_1_2)))))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_1)
                    .addComponent(Btn_0_1)
                    .addComponent(Btn_1_1)
                    .addComponent(Lbl_masukkan1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_2)
                    .addComponent(Btn_0_2)
                    .addComponent(Btn_1_2)
                    .addComponent(Lbl_masukkan2))
                .addGap(15, 15, 15)
                .addComponent(Lbl_Hasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Or, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_And, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Not, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Nor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Nand, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Xor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Xnor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AndActionPerformed
        // TODO add your handling code here:
        if(!"-".equals(Lbl_masukkan1.getText()) && !"-".equals(Lbl_masukkan2.getText())){
            satu=Integer.parseInt(Lbl_masukkan1.getText());
            dua=Integer.parseInt(Lbl_masukkan2.getText());
            if(satu==0&&dua==0){
//                Txt_Hasil.setText(Integer.toString(0));
                Lbl_Hasil.setText(nol);
            }else if(satu==1&&dua==0){
//                Txt_Hasil.setText(Integer.toString(0));
                Lbl_Hasil.setText(nol);
            }else if(satu==0&&dua==1){
//                Txt_Hasil.setText(Integer.toString(0));
                Lbl_Hasil.setText(nol);
            }else if(satu==1&&dua==1){
//                Txt_Hasil.setText(Integer.toString(1));
                Lbl_Hasil.setText(satu1);
            }else{
//                Txt_Hasil.setText(error);
                Lbl_Hasil.setText(error);
            }
        }
    }//GEN-LAST:event_Btn_AndActionPerformed

    private void Btn_OrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OrActionPerformed
        // TODO add your handling code here:
        if(!"-".equals(Lbl_masukkan1.getText()) && !"-".equals(Lbl_masukkan2.getText())){
            satu=Integer.parseInt(Lbl_masukkan1.getText());
            dua=Integer.parseInt(Lbl_masukkan2.getText());
            if(satu==0&&dua==0){
//                Txt_Hasil.setText(Integer.toString(0));
                Lbl_Hasil.setText(nol);
            }else if(satu==1&&dua==0){
//                Txt_Hasil.setText(Integer.toString(1));
                Lbl_Hasil.setText(satu1);
            }else if(satu==0&&dua==1){
//                Txt_Hasil.setText(Integer.toString(1));
                Lbl_Hasil.setText(satu1);
            }else if(satu==1&&dua==1){
//                Txt_Hasil.setText(Integer.toString(1));
                Lbl_Hasil.setText(satu1);
            }else{
//                Txt_Hasil.setText(error);
                Lbl_Hasil.setText(error);
            }
        }
    }//GEN-LAST:event_Btn_OrActionPerformed

    private void Btn_NandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NandActionPerformed
        // TODO add your handling code here:
        if(!"-".equals(Lbl_masukkan1.getText()) && !"-".equals(Lbl_masukkan2.getText())){
            satu=Integer.parseInt(Lbl_masukkan1.getText());
            dua=Integer.parseInt(Lbl_masukkan2.getText());
            if(satu==1&&dua==1){
//                Txt_Hasil.setText(Integer.toString(0));
                Lbl_Hasil.setText(nol);
            }else if(satu==1&&dua==0){
//                Txt_Hasil.setText(Integer.toString(1));
                Lbl_Hasil.setText(satu1);
            }else if(satu==0&&dua==1){
//                Txt_Hasil.setText(Integer.toString(1));
                Lbl_Hasil.setText(satu1);
            }else if(satu==0&&dua==0){
//                Txt_Hasil.setText(Integer.toString(1));
                Lbl_Hasil.setText(satu1);
            }else{
//                Txt_Hasil.setText(error);
                Lbl_Hasil.setText(error);
            }
        }
    }//GEN-LAST:event_Btn_NandActionPerformed

    private void Btn_NorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NorActionPerformed
        // TODO add your handling code here:
        if(!"-".equals(Lbl_masukkan1.getText()) && !"-".equals(Lbl_masukkan2.getText())){
            satu=Integer.parseInt(Lbl_masukkan1.getText());
            dua=Integer.parseInt(Lbl_masukkan2.getText());
            if(satu==0&&dua==0){
//                Txt_Hasil.setText(Integer.toString(1));
                Lbl_Hasil.setText(satu1);
            }else if(satu==1&&dua==0){
//                Txt_Hasil.setText(Integer.toString(0));
                Lbl_Hasil.setText(nol);
            }else if(satu==0&&dua==1){
//                Txt_Hasil.setText(Integer.toString(0));
                Lbl_Hasil.setText(nol);
            }else if(satu==1&&dua==1){
//                Txt_Hasil.setText(Integer.toString(0));
                Lbl_Hasil.setText(nol);
            }else{
//                Txt_Hasil.setText(error);
                Lbl_Hasil.setText(error);
            }
        }
    }//GEN-LAST:event_Btn_NorActionPerformed

    private void Btn_NotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NotActionPerformed
        // TODO add your handling code here:
        if(!"-".equals(Lbl_masukkan1.getText()) && "-".equals(Lbl_masukkan2.getText())){
            satu=Integer.parseInt(Lbl_masukkan1.getText());
            if(!"-".equals(Lbl_masukkan1.getText())){
                Btn_0_2.setEnabled(false);
                Btn_1_2.setEnabled(false);
                if(satu==1){
//                Txt_Hasil.setText(Integer.toString(0));
                    Lbl_Hasil.setText(nol);
                }else if(satu==0){
//                Txt_Hasil.setText(Integer.toString(1));
                    Lbl_Hasil.setText(satu1);
                }else{
//                Txt_Hasil.setText(error);
                    Lbl_Hasil.setText(error);
                }  
            }
        }else if("-".equals(Lbl_masukkan1.getText()) && !"-".equals(Lbl_masukkan2.getText())){
            dua=Integer.parseInt(Lbl_masukkan2.getText());
            if(!"-".equals(Lbl_masukkan2.getText())){
                Btn_0_1.setEnabled(false);
                Btn_1_1.setEnabled(false);
                if(dua==1){
//                Txt_Hasil.setText(Integer.toString(0));
                    Lbl_Hasil.setText(nol);
                }else if(dua==0){
//                Txt_Hasil.setText(Integer.toString(1));
                    Lbl_Hasil.setText(satu1);
                }else{
//                Txt_Hasil.setText(error);
                    Lbl_Hasil.setText(error);
                }  
            }
        }
    }//GEN-LAST:event_Btn_NotActionPerformed

    private void Btn_XorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_XorActionPerformed
        // TODO add your handling code here:
        if(!"-".equals(Lbl_masukkan1.getText()) && !"-".equals(Lbl_masukkan2.getText())){
            satu=Integer.parseInt(Lbl_masukkan1.getText());
            dua=Integer.parseInt(Lbl_masukkan2.getText());
            if(satu==0&&dua==0){
//                Txt_Hasil.setText(Integer.toString(0));
                Lbl_Hasil.setText(nol);
            }else if(satu==1&&dua==1){
//                Txt_Hasil.setText(Integer.toString(0));
                Lbl_Hasil.setText(nol);
            }else if(satu==0&&dua==1){
//                Txt_Hasil.setText(Integer.toString(1));
                Lbl_Hasil.setText(satu1);
            }else if(satu==1&&dua==0){
//                Txt_Hasil.setText(Integer.toString(1));
                Lbl_Hasil.setText(satu1);
            }else{
//                Txt_Hasil.setText(error);
                Lbl_Hasil.setText(error);
            }
        }
    }//GEN-LAST:event_Btn_XorActionPerformed

    private void Btn_XnorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_XnorActionPerformed
        // TODO add your handling code here:
        if(!"-".equals(Lbl_masukkan1.getText()) && !"-".equals(Lbl_masukkan2.getText())){
            satu=Integer.parseInt(Lbl_masukkan1.getText());
            dua=Integer.parseInt(Lbl_masukkan2.getText());
            if(satu==0&&dua==0){
//                Txt_Hasil.setText(Integer.toString(1));
                Lbl_Hasil.setText(satu1);
            }else if(satu==1&&dua==1){
//                Txt_Hasil.setText(Integer.toString(1));
                Lbl_Hasil.setText(satu1);
            }else if(satu==0&&dua==1){
//                Txt_Hasil.setText(Integer.toString(0));
                Lbl_Hasil.setText(nol);
            }else if(satu==1&&dua==0){
//                Txt_Hasil.setText(Integer.toString(0));
                Lbl_Hasil.setText(nol);
            }else{
//                Txt_Hasil.setText(error);
                Lbl_Hasil.setText(error);
            }
        }
    }//GEN-LAST:event_Btn_XnorActionPerformed

    private void Btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ResetActionPerformed
        // TODO add your handling code here:
        Lbl_masukkan1.setText("-");
        Lbl_masukkan2.setText("-");
        Lbl_Hasil.setText("Hasil gerbang logika : - ");
        Btn_0_1.setEnabled(true);
        Btn_1_1.setEnabled(true);
        Btn_0_2.setEnabled(true);
        Btn_1_2.setEnabled(true);
    }//GEN-LAST:event_Btn_ResetActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new NewJFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void Btn_0_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_0_1ActionPerformed
        // TODO add your handling code here:
        Lbl_masukkan1.setText(nol_1);
    }//GEN-LAST:event_Btn_0_1ActionPerformed

    private void Btn_0_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_0_2ActionPerformed
        // TODO add your handling code here:
        Lbl_masukkan2.setText(nol_2);
    }//GEN-LAST:event_Btn_0_2ActionPerformed

    private void Btn_1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_1_1ActionPerformed
        // TODO add your handling code here:
        Lbl_masukkan1.setText(satu_1);
    }//GEN-LAST:event_Btn_1_1ActionPerformed

    private void Btn_1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_1_2ActionPerformed
        // TODO add your handling code here:
        Lbl_masukkan2.setText(satu_2);
    }//GEN-LAST:event_Btn_1_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formKalkulatorGL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formKalkulatorGL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formKalkulatorGL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formKalkulatorGL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formKalkulatorGL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_0_1;
    private javax.swing.JButton Btn_0_2;
    private javax.swing.JButton Btn_1_1;
    private javax.swing.JButton Btn_1_2;
    private javax.swing.JButton Btn_And;
    private javax.swing.JButton Btn_Nand;
    private javax.swing.JButton Btn_Nor;
    private javax.swing.JButton Btn_Not;
    private javax.swing.JButton Btn_Or;
    private javax.swing.JButton Btn_Reset;
    private javax.swing.JButton Btn_Xnor;
    private javax.swing.JButton Btn_Xor;
    private javax.swing.JLabel Lbl_1;
    private javax.swing.JLabel Lbl_2;
    private javax.swing.JLabel Lbl_Hasil;
    private javax.swing.JLabel Lbl_masukkan1;
    private javax.swing.JLabel Lbl_masukkan2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        
    }
}
